name: Update NBU JSON

on:
  schedule:
    - cron: '30 21 * * *' # 00:30 Kyiv time (UTC+3) = 21:30 UTC previous day
  workflow_dispatch:

jobs:
  update-nbu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Update NBU data
        run: python tools/update_nbu_json.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/data/nbu-history.json
          git commit -m "daily nbu update"
          git push
